### PR TITLE
bumps to 1.5.0

### PR DESCRIPTION
**Pull request by ignasi35**
Supersedes #117

### CODE REVIEW

**Comment by ignasi35** [comment]
There's a valid error on a test:

```
[info]   java.lang.IllegalArgumentException: No default service discovery implementation configured in `akka.discovery.method`. Make sure to configure this setting to your preferred implementation such as 'akka-dns' in your application.conf (from the akka-discovery module).
```

**Review by marcospereira — APPROVED** [review]

**Review by TimMoore — CHANGES_REQUESTED** [review]
Same comments as on #213: deployment instructions should be updated and tested, or else taken out to be replaced later.

**Comment by ignasi35** [comment]
@TimMoore I'd rather have this PR merged and do the remove of deployment info separately

**Comment by octonato** [comment]
@ignasi35, yesterday we agreed that we won't do that and instead archive it and remove the 1.5.0 branch.

**Comment by ignasi35** [comment]
> @ignasi35, yesterday we agreed that we won't do that and instead archive it and remove the 1.5.0 branch.

you're right. Completely forgot 🤦🏼‍♂️

**Pull request closed without merging**
