### PR TITLE
Enable MetricsService

### PR DESCRIPTION
**Pull request by katejim**
Enable MetricsService [#16](https://github.com/lagom/online-auction-scala/issues/16)

### CODE REVIEW

**Comment by ignasi35** [comment]
Thanks for this @katejim. I just tested it and there seems to be an issue. Either on the Lagom core code or in our docs (linked on #16 --> http://www.lagomframework.com/documentation/1.3.x/scala/ServiceClients.html#circuit-breaker-metrics).

The PR looks good to me when I test it I'm not sure it works as expected. When I query the `_status` endpoint to check on the metrics I never get any any info:

```
$ curl http://localhost:55320/_status/circuit-breaker/current | jq .
[]
```

**Expected** :

If I reproduce the test using `online-auction-java` while `elasticsearch` is turned off I get the expected result:

```
$ curl http://localhost:55320/_status/circuit-breaker/current | jq .
[
  {
    "id": "elastic-search",
    "timestamp": 1488461564.983,
    "state": "closed",
    "totalSuccessCount": 0,
    "totalFailureCount": 1,
    "latencyMicros": {
      "median": 13255,
      "percentile98th": 13255,
      "percentile99th": 13255,
      "percentile999th": 13255,
      "mean": 13255,
      "min": 13255,
      "max": 13255
    },
    "throughputOneMinute": 0.18400888292586468,
    "failedThroughputOneMinute": 0.18400888292586468
  }
]
```

**Comment by ignasi35** [comment]
Hi @katejim I reported https://github.com/lagom/lagom/issues/572 but I suspect I know what's going on.

I think if we setup an explicit CircuitBreaker we'll get metrics. The issue I mentioned on my previous comment could be a side effect of https://github.com/lagom/lagom/issues/532 which will be fixed in 1.3.1

**Comment by TimMoore** [comment]
@ignasi35 should we undo the change to add individual circuit breakers now that https://github.com/lagom/lagom/issues/532 is fixed?

**Comment by ignasi35** [comment]
We have several options (all of them focused on [ElasticSearch.scala](https://github.com/lagom/online-auction-scala/blob/master/search-impl/src/main/scala/com/example/elasticsearch/Elasticsearch.scala#L13-L20)):
 * remove the one-CB-per-call altogether
 * remove the one-CB-per-call and create one default circuit breaker 
 * leave a single one-CB-per-call <-- this would be my choice. One call would get a custom CB while the other call would get the default.

Customising CB's is a feature not very showcased in our sample apps and keeping parts of the work done is worth it.

**Pull request merged**
