### PR TITLE
Update ItemRepository to use promises

### PR DESCRIPTION
**Pull request by fgfernandez0321**
Hi @TimMoore,

I updated `ItemRepository` to use promises to avoid `var` declarations based on this issue: https://github.com/lagom/online-auction-scala/issues/90 and according to Lagom documentation. Also, the static values were formalized in constants using `ItemRepository` companion object.

### CODE REVIEW

**Comment by renatocaval** [comment]
@fgfernandez0321 there is conflict in this PR, can you solve it? We can merge as soon as this gets resolved. 

Thanks

**Comment by fgfernandez0321** [comment]
Hi @renatocaval, @ignasi35 

Conflicts solved.

**Comment by renatocaval** [comment]
Thanks @fgfernandez0321!

**Comment by fgfernandez0321** [comment]
Hi @renatocaval 

You're welcome. It's my pleasure to collaborate with the team. 

This issue https://github.com/lagom/online-auction-scala/issues/90 can be closed with this solution.

Regards

**Pull request merged**
